### PR TITLE
Fix not updating if calling using same image path with different data

### PR DESCRIPTION
**Pull request by edeetee**
Sets image to /dev/null then back to tell it to update.
I'm using this in a script that on repeat will download an image to a file
#1

### CODE REVIEW

**Comment by RaitaroH** [comment]
@edeetee this makes no sense to me. Can you tell me what you get from this command:
```
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.dumpCurrentLayoutJS | grep "Image"
```
You should at least get the image you set as an wallpaper.

**Comment by RaitaroH** [comment]
I cannot reproduce your issue at all. Even if plasma decides to fix itself after you setting the image to dev/null it still means you need to undo the change to make the script do its job... In that case what is the point of this PR? I will post this in the readme, but tell me if when you undo the modification, does ksetwallpaper work for you as described in the updated readme?

**Comment by RaitaroH** [comment]
Ah well, let it be as might be.
I still have no idea why you have this issue, nor why this works. But if it works whatever.

**Comment by edeetee** [comment]
I'll do some more testing over the next couple of days. Just had it not updating if I used the same image location (like called it with the same parameters after changing the image at that location). I'll make sure this is actually changed or if it was something else I did haha, thank :)

**Pull request merged**
